{block content}

{if $galerie['muze_pridavat']}<p class="config"><a href="{plink Galerie:add}" class="add">Přidat novou galerii</a></p>{/if}

{if count($galerie['galerie'])}
	{foreach $galerie['galerie'] as $jednaGalerie}
		<div class="odkaz-na-galerii">
			<h2><a href="{plink Galerie:galerie, $jednaGalerie['id']}">{$jednaGalerie['nazev']}</a></h2>
			{if $jednaGalerie['muze_editovat']}
				<p class="config">
					{if $jednaGalerie['muze_editovat']}<a href="{plink Galerie:edit, $jednaGalerie['id']}" class="edit">Upravit</a>{/if}
					{if $jednaGalerie['muze_editovat']}<a href="{plink delete!, $jednaGalerie['id']}" class="delete">Smazat</a>{/if}
					{if $jednaGalerie['muze_editovat']}<a href="{plink Galerie:pridatFotky, $jednaGalerie['id']}" class="add">Přidat fotky do galerie</a>{/if}
					{if $jednaGalerie['muze_editovat']}<a href="{plink Galerie:pridatVidea, $jednaGalerie['id']}" class="add">Přidat videa do galerie</a>{/if}
				</p>
			{/if}
			{control fotka:profilova, $jednaGalerie['id_fotky']}
			<dl>
				<dt>Datum zveřejnění</dt>
					{if $jednaGalerie['datum_zverejneni'] !== NULL}
					<dd>{$jednaGalerie['datum_zverejneni']|datum}{if !empty($jednaGalerie['datum_aktualizace'])} (Aktualizováno: {$jednaGalerie['datum_aktualizace']|datum}){/if}</dd>
				{else}
					<dd>Zatím nezveřejněno.</dd>
				{/if}
				<dt>Počet zobrazení</dt>
					<dd>{$jednaGalerie['pocet_zhlednuti']}&times;</dd>
				{if $jednaGalerie['typ'] == 'interni'}<dt>Počet fotografií</dt>
					<dd>{$jednaGalerie['pocet_fotografii']}</dd>{/if}
				{if $jednaGalerie['typ'] == 'rajce'}<dt>Počet fotografií</dt>
					<dd>galerie je vložená ze serveru Rajče.cz</dd>{/if}
				<dt>Počet videí</dt>
					<dd>{$jednaGalerie['pocet_videi']}</dd>
			</dl>
			{if !empty($jednaGalerie['text'])}
				{block|texy}{$jednaGalerie['text']|truncate:50}{/block}
			{/if}
		</div>
	{/foreach}
{else}
	<p class="flash warning">Žádné galerie nebyly nalezeny.</p>
{/if}