@{block #content}

{widget souvisejici 'galerie', $galerie['id'] }

{include 'nastaveni.phtml'}

{if !empty($galerie['text'])}
	{block|texy}{$galerie['text']}{/block}
{/if}

{snippet galerie}
{if count($fotky['fotky'])}
	{foreach $fotky['fotky'] as $fotka}
		{widget fotka:nahled $fotka}
	{/foreach}
{else}
<p class="warning">V galerii nejsou žádné fotogfafie ani videa.{if $fotky['muze_pridavat'] == true} <a href="{plink Galerie:pridatFotky, $galerie['id']}" class="add">Přidat nové!</a>{/if}</p>
{/if}
{/snippet}
