@{block content}

{if count($vysledky['vysledky'])}
	{foreach $vysledky['vysledky'] as $soutez => $vysledkySouteze}
		{foreach $vysledkySouteze as $kategorie => $vysledkyKategorie}
			{if !$iterator->isFirst() && $nahled}<h1>{$nadpis}</h1>{/if}
<table class="prehled zalomit-za">
	<caption>Výsledky kategorie <span class="{$kategorie|webalize}">{$kategorie}</span> v soutěži <span class="soutez-{$soutez|webalize}">{$soutez}</span></caption>
	<thead>
		<tr>
			<th rowspan="2">Pořadí</th><th rowspan="2">Družstvo</th>{if $vysledkyKategorie['jeLepsiCas']}<th rowspan="2">První terč</th>{/if}<th rowspan="2">Výsledný čas</th><th rowspan="2">Získané body</th>{if $vysledkyKategorie['jePoradiPred'] || $vysledkyKategorie['jePoradiPo']}<th{if $vysledkyKategorie['jePoradiPred'] && $vysledkyKategorie['jePoradiPo']} colspan="3"{/if}>Pořadí v soutěži{/if}</th>
		</tr>
		<tr>
			{if $vysledkyKategorie['jePoradiPred']}<th>Před</th>{/if}{if $vysledkyKategorie['jePoradiPo'] && $vysledkyKategorie['jePoradiPred']}<th></th>{/if}{if $vysledkyKategorie['jePoradiPo']}<th>Po</th>{/if}
		</tr>
	</thead>
	<tbody>
{foreach $vysledkyKategorie['vysledky'] as $vysledek}
	<tr>
	     <td class="poradi">{ifset $vysledek['poradi']}{$vysledek['poradi']}.{/if}</td>
	     <td>{ifset $vysledek['druzstvo']}<a href="{plink Druzstva:druzstvo, $vysledek['id_druzstva']}" title="Zobrazit informace o družstvu">{$vysledek['druzstvo']}</a>{else}<p>&nbsp;</p>{/if}</td>
          {if $vysledkyKategorie['jeLepsiCas']}<td class="cas">{if $vysledek['lepsi_cas'] != 0} {$vysledek['lepsi_cas']} {$vysledek['lepsi_terc']|upper}{/if}</td>{/if}
          <td class="cas">{ifset $vysledek['vysledny_cas']}{$vysledek['vysledny_cas']|vyslednyCas}{/if}</td>
          <td class="body">{ifset $vysledek['body']}{$vysledek['body']}{/if}</td>
		{if $vysledkyKategorie['jePoradiPred']}<td class="poradi">{if $vysledek['poradiPredZavodem'] != 0}{$vysledek['poradiPredZavodem']}.{/if}</td>{/if}
		{if $vysledkyKategorie['jePoradiPo'] && $vysledkyKategorie['jePoradiPred']}<td class="ukazatel-prubehu">{if $vysledek['poradiPredZavodem'] > $vysledek['poradiPoZavodu'] && $vysledek['poradiPoZavodu'] != 0}&uarr;{/if}{if $vysledek['poradiPredZavodem'] < $vysledek['poradiPoZavodu'] && $vysledek['poradiPredZavodem'] != 0}&darr;{/if}{if $vysledek['poradiPredZavodem'] == $vysledek['poradiPoZavodu'] && $vysledek['poradiPredZavodem'] != 0}={/if}</td>{/if}
		{if $vysledkyKategorie['jePoradiPo']}<td class="poradi">{ifset $vysledek['poradiPoZavodu']}{$vysledek['poradiPoZavodu']}.{/if}</td>{/if}
	</tr>
{/foreach}
	</tbody>
</table>
			{if !$nahled}<p><a href="{plink Zavody:vysledky, $zavod['id']}" class="printer">Zobrazit verzi výsledků pro tisk</a></p>{/if}
		{/foreach}
	{/foreach}
{else}
	{if $vysledky['muze_editovat'] == true}<p><a href="{plink Zavody:pridatVysledky, $zavod['id']}" title="Přidání výsledků k závodu" class="add">Přidat nové výsledky k závodu</a></p>{/if}
{/if}
