{block content}

{* Odkazy na předchozí a následující závody *}
<div class="relativni-odkazy">
	{if !empty($predchozi)}<div class="predchozi"><p>&larr; předchozí závod : <a href="{plink Zavody:zavod, $predchozi['id']}" title="Předchozí závod">{$predchozi['nazev']}</a></p><p>{$predchozi['datum']|datum:1:1:0}</p></div>{/if}
	{if !empty($nasledujici)}<div class="nasledujici"><p><a href="{plink Zavody:zavod, $nasledujici['id']}" title="Následující závod">{$nasledujici['nazev']}</a> : následující závod &rarr;</p><p>{$nasledujici['datum']|datum:1:1:0}</p></div>{/if}
</div>

{* Odkaz na editaci závodu *}

{* Informace o závodu *}
<h2>Informace o závodu{if $zavod['muze_editovat'] == true} [<a href="{plink Zavody:edit, $zavod['id']}" title="Úprava informací o závodu" class="edit">upravit informace o závodu</a>]{/if}</h2>

<div class="sdileni-zavodu">
	{control mapa, array('nazev' => $zavod['nazev'], 'odkaz' => $presenter->link('Zavody:zavod', $zavod['id']), 'sirka' => $zavod['sirka'], 'delka' => $zavod['delka'])}

	<dl>
		<dt>Exportovat do kalendáře</dt>
		<dd class="kalendar"><a href="{plink Kalendar:liga}">Všechny závody ve formátu iCal</a></dd>
		<dd class="kalendar"><a href="{plink Kalendar:zavod, $zavod->id}">Tento závod ve formátu iCal</a></dd>
		<dd class="kalendar"><a href="http://www.google.com/calendar/render?cid={$adresaLigy}{plink Kalendar:liga}" target="_blank">Všechny závody do <img src="https://www.google.com/calendar/images/calendar_plus_cs.gif" border=0></a></dd>
	</dl>
</div>

{if $zavod['zruseno'] == true}<p class="warning">Tento závod byl zrušen.</p>{/if}
<dl>
	<dt>Datum</dt><dd>{$zavod['datum']|datum:1:1:0}</dd>

	<dt>Pořadatel{if $zavod['muze_editovat']} [<a href="{plink Zavody:edit, $zavod['id']}" title="Úprava informací o závodu" class="edit">vybrat jiného pořadatele</a>]{/if}</dt>
	{foreach $zavod['poradatele'] as $poradatel}
		<dd><a href="{plink Sbory:sbor, $poradatel['id']}" title="Informace o sboru">{$poradatel['nazev']} (okres {$poradatel['okres']})</a></dd>
		{if $zavod['muze_editovat']}<dd><a href="{plink Sbory:edit, $poradatel['id'], $backlink}" class="edit">Upravit informace o tomto sboru</a></dd>{/if}
	{/foreach}

	<dt>Místo konání{if $zavod['muze_editovat']} [<a href="{plink Zavody:edit, $zavod['id']}" title="Úprava informací o závodu" class="edit">změnit místo</a>]{/if}</dt>
	<dd>{$zavod['misto']} (okres {$zavod['okres']})</dd>
	{if $zavod['muze_editovat']}<dd><a href="{plink Sportoviste:edit, $zavod['id_mista'], $backlink}" class="edit">Upravit informace o tomto sportovišti</a></dd>{/if}

	{if !empty($zavod['popis'])}<dt>Popis areálu</dt>{if $zavod['muze_editovat']}<dd><a href="{plink Sportoviste:edit, $zavod['id_mista'], $backlink}" class="edit">Upravit informace o tomto sportovišti</a></dd>{/if}<dd>{!$zavod['popis']|texy}</dd>{/if}

	{if count($zavod['poradatele'])}
	<dt>Kontakt</dt>
	{foreach $zavod['poradatele'] as $poradatel}
		{if $zavod['muze_editovat']}<dd><a href="{plink Sbory:edit, $poradatel['id'], $backlink}" class="edit">Změnit kontaktní osobu sboru {$poradatel['nazev']}</a></dd>{/if}
		{if !empty($poradatel['kontakt_kontakt'])}{if $zavod['muze_editovat']}<dd><a href="{plink Uzivatele:edit, $poradatel['kontakt_id']}" class="edit">Upravit následující kontaktní informace</a></dd>{/if}
		<dd>{!$poradatel['kontakt_jmeno'].' '.$poradatel['kontakt_prijmeni']."\n ".$poradatel['kontakt_email']."\n ".$poradatel['kontakt_kontakt']|texy}</dd>{/if}
	{/foreach}
	{/if}

	<dt>Terče{if $zavod['muze_editovat']} [<a href="{plink Zavody:edit, $zavod['id']}" title="Úprava informací o závodu" class="edit">vybrat jiné terče</a>]{/if}</dt>
	{if $zavod['muze_editovat']}<dd><a href="{plink Terce:edit, $zavod['id_tercu'], $backlink}" title="Úprava informací o terčích" class="edit">změnit informace o terčích</a></dd>{/if}
	<dd><a href="{plink Terce:terce, $zavod['id_tercu']}" title="Informace o terčích">{$zavod['terce']} ({$zavod['majitel_tercu']})</a></dd>

	<dt>Bodové tabulky</dt>
		<dd><a href="{plink Rocniky:vysledkyPredZavodem, $zavod['id']}" title="Průběžný stav bodů před začátkem závodů">Bodová tabulka před závodem</a></dd>
		{if !empty($nasledujici)}<dd><a href="{plink Rocniky:vysledkyPredZavodem, $nasledujici['id']}" title="Průběžný stav bodů po závodu">Bodová tabulka po závodu</a></dd>{else}<dd><a href="{plink Rocniky:vysledky, $zavod['rocnik']}" title="Průběžný stav bodů po závodu">Bodová tabulka po závodu</a></dd>{/if}


	<dt class="cleaner">Dosavadní rekordy dráhy platné do začátku závodu</dt>
{if count($zavod['dosavadniRekordy'])}
	{foreach $zavod['dosavadniRekordy'] as $soutez => $foo}
		<dd>na {block|texy:true}**{$zavod['terce']} terče** v soutěži **{$soutez}**{/block}<ul>
		{foreach $foo as $rekord}
			<li><a href="{plink Druzstva:druzstvo, $rekord['id']}" title="Informace o družstvu">{$rekord['druzstvo']}</a>, čas {$rekord['vysledny_cas']} s, <a href="{plink Zavody:zavod, $rekord['id_zavodu']}" title="Informace o závodu">{$rekord['zavod']}, {$rekord['datum']|substr:0:10|datum:0:0:0}</a></li>
		{/foreach}</ul></dd>
	{/foreach}
{else}
	<dd class="warning">Na této dráze se ještě nezávodilo.</dd>
{/if}
{if count($zavod['rekordy'])}
	<dt>Aktuální rekordy dráhy</dt>
	{foreach $zavod['rekordy'] as $soutez => $foo}
		<dd>na {block|texy:true}**{$zavod['terce']} terče** v soutěži **{$soutez}**{/block}<ul>
		{foreach $foo as $rekord}
			<li><a href="{plink Druzstva:druzstvo, $rekord['id']}" title="Informace o družstvu">{$rekord['druzstvo']}</a>, čas {$rekord['vysledny_cas']|vyslednyCas} s, <a href="{plink Zavody:zavod, $rekord['id_zavodu']}" title="Informace o závodu">{$rekord['zavod']}, {$rekord['datum']|substr:0:10|datum:0:0:0}</a></li>
		{/foreach}</ul></dd>
	{/foreach}
{/if}

{if count($rekordyLigy['dosavadni'])}
	<dt>Dosavadní rekordy ligy platné do začátku závodu</dt>
	{foreach $rekordyLigy['dosavadni'] as $soutez => $foo}
		<dd>na {block|texy:true}**{$zavod['terce']} terče** v soutěži **{$soutez}**{/block}<ul>
		{foreach $foo as $rekord}
			<li><a href="{plink Druzstva:druzstvo, $rekord['id_druzstva']}" title="Informace o družstvu">{$rekord['druzstvo']}</a>, čas {$rekord['vysledny_cas']|vyslednyCas} s, <a href="{plink Zavody:zavod, $rekord['id_zavodu']}" title="Informace o závodu">{$rekord['zavod']}, {$rekord['datum']|substr:0:10|datum:0:0:0}</a></li>
		{/foreach}</ul></dd>
	{/foreach}
{/if}
{if count($rekordyLigy['aktualni'])}
	<dt>Aktuální rekordy ligy</dt>
	{foreach $rekordyLigy['aktualni'] as $soutez => $foo}
		<dd>na {block|texy:true}**{$zavod['terce']} terče** v soutěži **{$soutez}**{/block}<ul>
		{foreach $foo as $rekord}
			<li><a href="{plink Druzstva:druzstvo, $rekord['id_druzstva']}" title="Informace o družstvu">{$rekord['druzstvo']}</a>, čas {$rekord['vysledny_cas']|vyslednyCas} s, <a href="{plink Zavody:zavod, $rekord['id_zavodu']}" title="Informace o závodu">{$rekord['zavod']}, {$rekord['datum']|substr:0:10|datum:0:0:0}</a></li>
		{/foreach}</ul></dd>
	{/foreach}
{/if}

{if count($predchoziKola)}
	<dt>Jiná kola pořádaná tímto sborem</dt>
	{foreach $predchoziKola as $kolo}
		<dd{if $kolo['zruseno']} class="zruseny-zavod"{/if}><a href="{plink Zavody:zavod, $kolo['id']}" title="Přejdi na závod">{$kolo['nazev']} {$kolo['datum']|substr:0:10|datum:0:0:0}</a> ({$kolo['terce']} terče)</dd>
	{/foreach}
{/if}

{if !empty($zavod['text'])}
	<dt>Poznámka</dt><dd>{!$zavod['text']|texy}</dd>
{/if}
<dt id="toc-materialy-pro-tisk">Materiály pro pořadatele soutěží určené pro tisk</dt>
	<dd><a class="printer" href="{plink Zavody:pripravaProKomentatora, $zavod['id']}">Informace o soutěži a soutěžních družstvech pro komentátora</a></dd>
	{if $zavod['aktivni_startovni_poradi']}<dd><a class="printer" href="{plink Zavody:startovniPoradi, $zavod['id']}">Startovní pořadí</a></dd>{/if}
	{if $zavod['aktivni_startovni_poradi']}<dd><a class="printer" href="{plink Zavody:vysledky, $zavod['id']}">{if count($vysledky['vysledky'])}Výsledky ze závodů{else}Formulář pro zapsání výsledků{/if}</a></dd>{/if}
	{if $zavod['aktivni_startovni_poradi']}<dd><a class="printer" href="{plink Zavody:vysledkyExcel, $zavod['id']}">Tabulka pro Microsoft Excel pro zapsání a tisk výsledků</a></dd>{/if}
{if 0 && $zavod['muze_hodnotit']}
	<dt>Ohodnoťte pořádání závodu</dt><dd>{control hodnoceni $zavod['id']}</dd>
{/if}

{control souvisejici "zavody", $zavod['id']}

</dl>

{control souvisejici "zavody", $zavod['id'], true}

{control prilohy "zavody", $zavod['id']}

{if $zavod['ustream_stav'] == 'ano'}<h2>Video přenos</h2><p class="ok">Z toho závodu je plánován živý video přenos.</p>{/if}

{if $vysledky['muze_editovat'] == true || count($vysledky['vysledky'])}
	<h2>Výsledky ze závodu{if $vysledky['muze_editovat'] == true && count($vysledky['vysledky'])} <a href="{plink Zavody:pridatVysledky, $zavod['id']}" title="Přidání výsledků k závodu" class="edit">upravit</a>{/if}</h2>
{/if}

{include 'vysledky.phtml', 'vysledky' => $vysledky, 'zavod' => $zavod}

{if $zavod['aktivni_startovni_poradi'] && count($startovni_poradi)}
	<h2 id="toc-startovni-poradi">Startovní pořadí</h2>
	{include 'startovniPoradi.phtml', 'startovni_poradi' => $startovni_poradi, 'zavod' => $zavod}
{/if}

<h2>Komentáře k závodu</h2>
{control diskuze $zavod->id, "zavody"}
