{* Šablona s kontakty *}

<table class="prehled">
	<thead>
		<tr>
			<th>Jméno a příjmení</th><th>Funkce</th><th>Kontakt</th><th>Sbor</th>
		</tr>
	</thead>
     <tbody>
		{foreach $kontaktniOsoby as $osoba}
		<tr>
			<td><a href="{plink Uzivatele:uzivatel, $osoba['id']}">{$osoba['jmeno']} {$osoba['prijmeni']}</a></td>
               <td>{if $osoba['kategorie'] == 'rada'}{$osoba['funkce']}{else}Pořadatel závodu <a href="{plink Zavody:zavod, $osoba['id_zavodu']}">{$osoba['funkce']}, {$osoba['datum_zavodu']|substr:0,10|datum:0:0:0}</a>{/if}</td>
               <td>{block|texy2}{!$osoba['kontakt']}
 E-mail: {$osoba['email']}{/block}</td>
               <td><a href="{plink Sbory:sbor, $osoba['id_sboru']}">{$osoba['sbor']}</a></td>
		</tr>
		{/foreach}
	</tbody>
</table>
