{block #content}

{if count($sablony['leve'])}
<div class="sablonyclanku-leve">
	{foreach $sablony['leve'] as $sablona}
		{control fotka:sablonaclanku $sablona['obrazek_id']}
	{/foreach}
	<span class="cleaner"></span>
</div>
{/if}

{if count($sablony['prave'])}
<div class="sablonyclanku-prave">
	{foreach $sablony['prave'] as $sablona}
		{control fotka:sablonaclanku $sablona['obrazek_id']}
	{/foreach}
	<span class="cleaner"></span>
</div>
{/if}