<object width="{$control->width}" height="{$control->height}"
    data="data:application/x-silverlight-2,"
    type="application/x-silverlight-2"
    standby="Grafy">
    <param name="source" value="{$control->source}"/>
    <param name="initParams" value="dataUrl={$hostUri}{$control->dataUrl}"/>
</object>


    {*<div id="silverlightControlHost">
        <object data="data:application/x-silverlight-2," type="application/x-silverlight-2" width="100%" height="100%">
		  <param name="source" value="/liga/document_root/grafy/Grafy.xap"/>
		  <param name="onError" value="onSilverlightError" />
		  <param name="background" value="white" />
		  <param name="minRuntimeVersion" value="3.0.40624.0" />
		  <param name="autoUpgrade" value="true" />
		  <param name="initParams" value="dataUrl=http://localhost/liga/document_root/druzstva/graf-druzstva/{$druzstvo['id']}"/>
		  <a href="http://go.microsoft.com/fwlink/?LinkID=149156&v=3.0.40624.0" style="text-decoration:none">
 			  <img src="http://go.microsoft.com/fwlink/?LinkId=108181" alt="Get Microsoft Silverlight" style="border-style:none"/>
		  </a>
	    </object><iframe id="_sl_historyFrame" style="visibility:hidden;height:0px;width:0px;border:0px"></iframe></div>*}
