{* Šablona pro výpis diskuzí *}

{block #content}

{if count($diskuze['diskuze'])}
	{if $diskuze['muze_pridavat'] == true}<p class="config"><a href="{plink Diskuze:zeptatse, $diskuze['id_tematu'], $diskuze['id_souvisejiciho']}" class="add">Založit nové téma!</a></p>{/if}
	{foreach $diskuze['diskuze'] as $disk}
		{if !empty($diskuze['souvisejiciTabulka'])}
			<h3>Diskuze na téma: <a href="{plink Diskuze:diskuze, $disk['id_diskuze']}" title="Přejít na diskuzi">{$disk['tema_diskuze']}</a></h3>
		{/if}

		{if empty($diskuze['souvisejiciTabulka'])}
			{* Související odkaz *}
			{control souvisejici "diskuze", $disk['id_diskuze']}
		{/if}

		{* Výpis vlastních komentářů *}
		{* snippet *}
		{* snippet 'komentare'.$disk['id_diskuze'] *}
			{include '@komentare.phtml', 'komentare' => $disk['komentare']}
		{* /snippet *}
		{* /snippet *}

		{include 'nastaveni.phtml', 'diskuze' => $disk}
	{/foreach}
	{if $diskuze['muze_pridavat'] == true}<p><a href="{plink Diskuze:zeptatse, $diskuze['id_tematu'], $diskuze['id_souvisejiciho']}" class="add">Založit nové téma!</a></p>{/if}
{else}
	<p class="warning">V diskuzi není zatím žádné téma.{if $diskuze['muze_pridavat'] == true} <a href="{plink Diskuze:zeptatse, $diskuze['id_tematu'], $diskuze['id_souvisejiciho']}" class="add">Přidat nové!</a>{/if}</p>
{/if}
