{layout none}

<!DOCTYPE html>
<head>
	<title>Závažná chyba</title>
	<meta charset="utf-8">
	<meta name="robots" content="noindex">
	<style>
		body { color: #333; background: white; width: 500px; margin: 100px auto; }
		h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0; }
		p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0; }
		small { font-size: 70%; color: gray }
	</style>
</head>
<body>

	<h1>Závažná chyba</h1>

	<p>Omlouváme se, ale vyskytla se závažná chyba, která znemožňuje načtení stránky. Podrobnosti o chybě byly uloženy a pokusíme se ji co nejdříve odstranit.</p>
	<p>Zkuste stránku obnovit pomocí tlačítka F5 nebo jiným obvyklým způsobem. Pokud chyba přetrvává, zkuste se vrátit na předchozí stránku.</p>

</body>
</html>
