@{block content}

{if $clanky['muze_pridavat']}<p class="config"><a href="{plink Clanky:add}" title="Přidat nový článek" class="add">Přidat nový článek</a></p>{/if}

{if count($clanky['clanky'])}
	{foreach $clanky['clanky'] as $clanek}
		<div class="clanek{if !empty($clanek->cssstyl)} clanek-{$clanek->cssstyl}{/if}">{include ../../templates/Clanky/@Clanky.clanek.phtml, 'clanek' => $clanek, 'fulltext' => false}<span class="cleaner"></span></div>
	{/foreach}
{else}
	<p>Nebyly přidány žádné články.</p>
{/if}

<p class="center"><a href="{plink Clanky:default}">&rArr; Přejít na všechny články</a></p>

<div class="dva-sloupce">
	<div class="sloupec">@{widget anketa}</div>
	<div class="sloupec"></div>
</div>
