@{block content}

<h2>Údržba stránek</h2>
<dl>	
	<dt><a href="{plink Sprava:kontrola}">Kontrola</a></dt>
	<dd>Zkontroluje, zda jsou vyplněny všechny potřebné údaje pro chod soutěží.</dd>
	
	<dt><a href="{plink Sprava:udrzba}">Údržba</a></dt>
	<dd>Provede automatickou údržbu webových stránek.</dd>
</dl>

<h2>Správa informací souvisejících se sportovní činností</h2>
<ul>	
	<li><a href="{plink Kategorie:default}">Správa sportovních kategorií</a></li>
	<li><a href="{plink Souteze:default}">Správa soutěží</a></li>
	<li><a href="{plink TypyTercu:default}">Správa typů terčů</a></li>
	<li><a href="{plink Terce:default}">Správa terčů</a></li>	
	<li><a href="{plink BodoveTabulky:default}">Správa bodových tabulek</a></li>
	<li><a href="{plink Sportoviste:default}">Správa sportovišť</a></li>
</ul>

<h2>Správa informací souvisejících se sbory a družstvy</h2>
<ul>
	<li><a href="{plink TypySboru:default}">Správa typů sborů</a></li>
	<li><a href="{plink Sbory:default}">Správa sborů</a></li>
	<li><a href="{plink Druzstva:default}">Správa družstev</a></li>
	<li><a href="{plink Mista:default}">Správa míst</a></li>
	<li><a href="{plink Okresy:default}">Správa okresů</a></li>
</ul>
	
<h2>Správa informací souvisejících s provozem stránek</h2>
<ul>	
	<li><a href="{plink Ankety:default}">Správa anket</a></li>
	<li><a href="{plink KategorieClanku:default}">Správa kategorií článků</a></li>
	<li><a href="{plink FunkceRady:default}">Správa funkcí rady</a></li>
	<li><a href="{plink Stranky:default}">Správa stránek</a></li>
	<li><a href="{plink Temata:default}">Správa témat diskuzního fóra</a></li>
	<li><a href="{plink Uzivatele:default}">Správa uživatelů</a></li>
	<li><a href="{plink Sledovani:default}">Správa sledování diskuzí</a></li>
</ul>
