{* Šablona pro výpis jednoho článku *}

{if $fulltext == false}<h2><a href="{plink Clanky:clanek, $clanek['id']}">{$clanek['nazev']}</a></h2>{/if}
{if $fulltext == false}{if $clanek['cssstyl'] == 'rada'}<h2><strong>Oznámení rady</strong></h2>{/if}{/if}
{if $clanek['muze_editovat'] == true || $clanek['muze_smazat'] == true}<p class="config">{if $clanek['muze_editovat'] == true}<a href="{link Clanky:edit, $clanek['id']}" title="Upravit tento článek" class="edit">Uprav</a>{/if}{if $clanek['muze_smazat'] == true} <a href="{plink delete!, $clanek['id']}" title="Smazat tento článek" class="delete">Smaž</a>{/if}</p>{/if}
{if $fulltext == false}<p class="clanek-zahlavi">Vystavil: <a href="{plink Uzivatele:uzivatel, $clanek['id_autora']}" title="Informace o autorovi">{$clanek['autor']}</a>, {ifset $clanek['datum_zverejneni']}{$clanek['datum_zverejneni']|datum:0:0:0}{else}nezveřejněno{/ifset}, komentáře: {$clanek['pocet_komentaru']}, přečteno: {$clanek['pocet_cteni']}&times;{if $clanek['posledni_aktualizace'] != ''}, <b>aktualizováno</b>{/if}</p>{/if}

{if $fulltext == true && ($clanek['muze_smazat'] == true || $clanek['muze_editovat'] == true)}<p class="config">{if $clanek['muze_editovat'] == true}<a href="{link Clanky:edit, $clanek['id']}" title="Upravit tento článek" class="edit">Upravit článek</a>{/if}{if $clanek['muze_smazat'] == true} <a href="{plink delete!, $clanek['id']}" title="Smazat tento článek" class="delete">Smazat článek!</a>{/if}</p>{/if}

{if $fulltext == true}
	<div class="perex">{!$clanek['perex']|texy}</div>
{else}
	<div class="perex">{!$clanek['perex']|texy}</div>
{/if}
{if $fulltext == false && !empty($clanek['text'])}<p><a href="{plink Clanky:clanek, $clanek['id']}">Pokračování v článku!</a></p>{/if}
{if $fulltext == true && !empty($clanek['text'])}{!$clanek['text']|texy}{/if}

{if $fulltext == true}
	{widget souvisejici "clanky", $clanek['id']}
{/if}

{if $fulltext == true}<p class="clanek-paticka">Vystavil: <a href="{plink Uzivatele:uzivatel, $clanek['id_autora']}" title="Informace o autorovi">{$clanek['autor']}</a> {ifset $clanek['datum_zverejneni']}{$clanek['datum_zverejneni']|datum:1:1:1}{if $clanek['posledni_aktualizace'] != ''}, <b>aktualizováno</b>{/if}{else}, nezveřejněno{/if}, přečteno: {$clanek['pocet_cteni']}&times;</p>{/if}
