{block content}

<p class="warning">Emailová adresa již byla jednou zaregistrována. Pokud se chcete opětovně přihlásit k tomuto účtu a nepamatujete si heslo, nechte si zaslat na uvedený email heslo nové.</p>

<p><a href="{plink Uzivatele:zapomenuteUdaje}" class="help fancybox">Nechat si vygenerovat nové heslo!</a></p>

<p><a href="{plink Uzivatele:add}" class="add">Znovu vyplnit registrační formulář</a> s jiným e-mailem!</p>