{* Šablona pro výpis diskuzí *}

@{block #content}

<div id="mapa" class="prehled-zavodu"></div>

<script type="text/javascript" src="http://api4.mapy.cz/loader.js"></script>
<script type="text/javascript">Loader.load();</script>


<script lang="text/javascript">
var center = SMap.Coords.fromPP({$stred['delka']}, {$stred['sirka']});
var m = new SMap(JAK.gel("mapa"), center, 13);
m.addDefaultLayer(SMap.DEF_BASE).enable();
m.addDefaultControls();

var layer = new SMap.Layer.Marker();
m.addLayer(layer);
layer.enable();

var body = new Array;

{foreach $body as $bod}
	var card = new SMap.Card();
	card.getHeader().innerHTML = "<strong>"+{$bod['nazev']}+"</strong>";

	body.push(SMap.Coords.fromPP({$bod['delka']}, {$bod['sirka']}));
	var marker = new SMap.Marker(SMap.Coords.fromPP({$bod['delka']}, {$bod['sirka']}), {$bod['id']}, { title: {$bod['nazev']}});
	//marker.decorate(SMap.Marker.Feature.Card, card);
	layer.addMarker(marker);
{/foreach}

var novyStred = m.computeCenterZoom(body, true);
m.setCenterZoom(novyStred[0], novyStred[1]);

m.addDefaultLayer(SMap.DEF_OPHOTO);
m.addDefaultLayer(SMap.DEF_OPHOTO0203);
m.addDefaultLayer(SMap.DEF_OPHOTO0406);
m.addDefaultLayer(SMap.DEF_TURIST);
m.addDefaultLayer(SMap.DEF_HISTORIC);
m.addDefaultLayer(SMap.DEF_BASE).enable();

var layerSwitch = new SMap.Control.Layer();
layerSwitch.addDefaultLayer(SMap.DEF_BASE);
layerSwitch.addDefaultLayer(SMap.DEF_OPHOTO);
layerSwitch.addDefaultLayer(SMap.DEF_TURIST);
layerSwitch.addDefaultLayer(SMap.DEF_OPHOTO0406);
layerSwitch.addDefaultLayer(SMap.DEF_OPHOTO0203);
layerSwitch.addDefaultLayer(SMap.DEF_HISTORIC);
m.addControl(layerSwitch,{ left:"8px", top:"9px"});
</script>