<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<meta name="description" content="{$liga['popis']}" />

	<title>{$title}</title>

	<!--link href="{$basePath}/liga/images/favicon.ico" rel="icon" type="image/x-icon" /-->

	<script type="text/javascript" src="{$basePath}/js/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery-ui-1.10.3.custom.min.js"></script>
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/themes/smoothness/jquery-ui-1.10.3.custom.css" type="text/css" />

	<script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>

	<script type="text/javascript" src="{$basePath}/js/jquery.rating/jquery.rating.pack.js"></script>
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/js/jquery.rating/jquery.rating.css" type="text/css" />

	<script type="text/javascript" src="{$basePath}/js/jquery.ui.datepicker-cs.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery-ui-timepicker-addon.js"></script>

	{control texyla}
	<link rel="stylesheet" href="{$basePath}/js/texyla/css/style.css" type="text/css">
	<link rel="stylesheet" href="{$basePath}/js/texyla/themes/default/theme.css" type="text/css">

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/js/chosen/chosen.css" type="text/css" />
	<script type="text/javascript" src="{$basePath}/js/chosen/chosen.jquery.min.js"></script>

	<!-- nette validace formulářů -->
	<script type="text/JavaScript" src="{$basePath}/js/live-form-validation.js"></script>

	<!-- fancybox pro fotky -->
	<link rel="stylesheet" href="{$basePath}/js/jquery.fancybox2/jquery.fancybox.css?v=2.1.4" type="text/css" media="screen" />
	<script type="text/javascript" src="{$basePath}/js/jquery.fancybox2/jquery.fancybox.pack.js?v=2.1.4"></script>

	<script type="text/javascript" src="{$basePath}/js/scripty.js"></script>

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css" />
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/liga/css/screen.css" type="text/css" />
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css" />

	<script type="text/JavaScript" src="{$basePath}/js/jquery.livequery.js"></script>
	<script type="text/JavaScript" src="{$basePath}/js/nette-ajax-form.js"></script>

	<script type="text/JavaScript" src="{$basePath}/js/jquery.tablesorter.min.js"></script>

	<script type="text/JavaScript" src="{$basePath}/js/jquery.cycle.lite.js"></script>

	<script type="text/JavaScript" src="{$basePath}/js/jquery.pnotify/jquery.pnotify.min.js"></script>
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/js/jquery.pnotify/jquery.pnotify.default.css" type="text/css" />

	<script type="text/JavaScript" src="{$basePath}/js/jquery.nette.dependentselectbox.js"></script>

	<script type="text/javascript" src="{$basePath}/js/ImageUploader/ImageUploader.js"></script>
	<script type="text/javascript" src="{$basePath}/js/ImageUploader/jquery.filedrop.js"></script>

	<script type="text/javascript" src="{$basePath}/js/lemmon-slider.js"></script>

	<!-- Obrázek pro sdílení na FB -->
	<!-- meta property="og:image" content="{$basePath}/liga/images/logo.png" -->
</head>

<body>
	<div id="main">
		<div id="zahlavi">
			<div id="hlavicka">
				<a href="{$basePath}/" title="Hlavní stránka" class="hlavni-odkaz">FSL CMS</a>
				<h3>Menu</h3>
				<ul id="menu">
					{foreach $menu as $odkaz}
					{if $odkaz['id'] !== NULL}<li class="{$odkaz['class']}"><a href="{link $odkaz['odkaz'], $odkaz['id']}"{if $odkaz['aktivni'] == true} class="aktivni"{/if}>{$odkaz['nazev']}<span></span></a></li>{else}<li class="{$odkaz['class']}"><a href="{link $odkaz['odkaz']}"{if $odkaz['aktivni'] == true} class="aktivni"{/if}>{$odkaz['nazev']}<span></span></a></li>{/if}
					{/foreach}
				</ul>
				<a href="Homepage:" class="hlavni-stranka"></a>
			</div>
		</div>

		<div id="hlavni-obsah">
			{control navigation:breadcrumbsLinks}

			<p class="tisk"><span>Tisk</span></p>

			{control aktualni}

			<h1>{$nadpis}</h1>

			{snippet flashes}
				{foreach $flashes as $flash}<p class="flash pnotify {$flash->type}">{!$flash->message|texy:true}</p>{/foreach}
			{/snippet}

			{include #content}
			<span class="cleaner"></span>
		</div>

		<div id="postrani">
			{control souteze}
			{control poradi}

			<div>
				{widget anketa}
				<span class="cleaner"></span>
			</div>

			{ifCurrent Sprava:login}
			{else}
				{control auth}
			{/ifCurrent}

			<span class="cleaner"></span>
		</div>
		<div id="patka">
			<h3>{$liga['nazev']}</h3>
			<p class="menu"><a href="{plink Clanky:}">Články</a> | {foreach $menu as $odkaz}
				{if $odkaz['id'] !== NULL}<a href="{link $odkaz['odkaz'], $odkaz['id']}"{if $odkaz['aktivni'] == true} class="aktivni"{/if}>{$odkaz['nazev']}</a>{else}<a href="{link $odkaz['odkaz']}"{if $odkaz['aktivni'] == true} class="aktivni"{/if}>{$odkaz['nazev']}</a>{/if} |
				{/foreach} <a href="{plink Sprava:}">Správa</a></p>
			<p>Redakční systém <a href="{$FSL_CMS_URL}">{$FSL_CMS}</a> v{$FSL_CMS_VERZE} &copy; 2010 &ndash; {$aktualniRok}</p>
		</div>
	</div>
</body>
</html>