<?php
header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds
?>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name=robots content=noindex>

		<style>
			body { color: #333; background: white; width: 500px; margin: 100px auto }
			h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
			p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
		</style>

		<title>Závažná chyba</title>
	</head>
	<body>
		<h1>Omlouváme se</h1>

		<p>Omlouváme se, ale vyskytla se závažná chyba, která znemožňuje zobrazení stránky. Podrobnosti o chybě byly uloženy a pokusíme se ji co nejdříve odstranit.</p>
		<p>Zkuste stránku obnovit pomocí tlačítka F5 nebo jiným obvyklým způsobem. Pokud chyba přetrvává, zkuste se vrátit na stránku zpět nebo navštívit naše stránky později.</p>

	</body>
</html>
<?php
exit;
