<?php

header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds

?>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name=robots content=noindex>

<style>
	body { color: #333; background: white; width: 500px; margin: 100px auto }
	h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
	p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
</style>

<title>Dočasná odstávka webu</title>
	</head>
	<body>
<h1>Omlouváme se</h1>

<p>Stránky jsou dočasně mimo provoz, probíhá údržba. Zkuste to prosím za pár minut.</p>
</body>
</html>
<?php

exit;
