@{block #content}

{widget souvisejici 'fotogalerie', $galerie['id'] }

{include 'galerie.phtml'}

{if !empty($galerie['text'])}
	{block|texy}{$galerie['text']}{/block}
{/if}

<iframe src="{$galerie['typ_key']}?insert=1&bgcolor=" name="hlavni" scrolling="auto" align="middle" width="680" height="850" frameborder="0">Omlouváme se, galerii nelze zobrazit ve Vašem prohlížeči z našich stránek. Můžete přejít na její originální verzi: <a href="{$galerie['typ_key']}">{$galerie['typ_key']}</a></iframe>
