{snippet}
<div class="prehled-soutezi">
	<h2>
		{if $control->relativni['predchozi'] == true}<!--a href="{link predchozi! }" class="ajax predchozi">&laquo;</a-->{/if}
		{!$nadpis|texy:true}
		{if $control->relativni['nasledujici'] == true}<!--a href="{link nasledujici! }" class="ajax">&raquo;</a-->{/if}
	</h2>
	<ul>
		{foreach $zavody as $zavod}
		<li class="zavod{if $zavod['zruseno'] == true} zruseny{/if}{if $zavod['vysledky'] == 1} byl{/if}{if $zavod['lze_prihlasit'] == 1} je{/if}"><span class="stav">{if $zavod['vysledky'] == 1}&check;{/if}{if $zavod['lze_prihlasit'] == 1}!{/if}</span><a href="{plink Zavody:zavod, $zavod->id}" title="Zobrazit informace o závodu"><span class="nazev">{$zavod->nazev}</span> <span class="datum">{$zavod->datum|date:'%d.%m.'}</span></a></li>
		{/foreach}
	</ul>
	{if $control->celkove_vysledky == true}
		<p class="celkove-vysledky"><a href="{plink Rocniky:vysledky, $control->rocnik}" title="Přejít na celkové výsledky ročníku">Bodová tabulka</a></p>
	{/if}
</div>
{/snippet}