{snippet}
<div id="dropbox">
	<span class="message">Obrázky k nahrání přetáhnout sem</span>
</div>
<script>
$(function(){

	var dropbox = $('#dropbox'),
		message = $('.message', dropbox);

	dropbox.filedrop({
		// The name of the $_FILES entry:
		paramname:'pic',

		maxfiles: 20,
		maxfilesize: 2, // in mb
		url: {link upload!},

		uploadFinished:function(i,file,response){
			if( response.status == 'ok' ) $.data(file).addClass('done').delay("1000").fadeOut();
			else { $.data(file).addClass('error'); alert(response.status); }
		},

		error: function(err, file) {
			switch(err) {
				case 'BrowserNotSupported':
					showMessage('Prohlížeč bohužel nepodporuje tento způsob nahrávání souborů.');
					break;
				case 'TooManyFiles':
					alert('Bylo vybráno příliš mnoho souborů.');
					break;
				case 'FileTooLarge':
					alert(file.name+' je příliš velký!');
					break;
				default:
					break;
			}
		},

		// Called before each upload is started
		beforeEach: function(file){
			if(!file.type.match(/^image\//)){
				alert('Only images are allowed!');

				// Returning false will cause the
				// file to be rejected
				return false;
			}
		},

		uploadStarted:function(i, file, len){
			createImage(file);
		},

		progressUpdated: function(i, file, progress) {
			$.data(file).find('.progress').width(progress);
		}

	});

	var template = '<div class="preview">'+
	'<span class="imageHolder">'+
		'<img />'+
		'<span class="uploaded"></span>'+
		'<span class="notuploaded"></span>'+
	'</span>'+
	'<div class="progressHolder">'+
		'<div class="progress"></div>'+
	'</div>'+
'</div>';

	function createImage(file){

		var preview = $(template),
			image = $('img', preview);

		var reader = new FileReader();

		image.width = 100;
		image.height = 100;

		reader.onload = function(e){

			// e.target.result holds the DataURL which
			// can be used as a source of the image:

			image.attr('src',e.target.result);
		};

		// Reading the file as a DataURL. When finished,
		// this will trigger the onload function above:
		reader.readAsDataURL(file);

		//message.hide();
		preview.appendTo(dropbox);

		// Associating a preview container
		// with the file, using jQuery's $.data():

		$.data(file,preview);
	}

	function showMessage(msg){
		message.html(msg);
	}

});
</script>
{/snippet}