@{block content}

{if $kategorie['muze_editovat'] == true}<p class="config"><a href="{plink edit}" class="add">Přidat novou kategorii</a></p>{/if}

{if count($kategorie['kategorie'])}
{widget kategorieForm begin}
<table class="prehled">
<thead>
	<tr>
	     <th colspan="2">Pořadí</th><th>Kategorie</th>{if $kategorie['muze_editovat'] == true}<th>Správa</th>{/if}
	</tr>
</thead>
<tbody class="sortable">
	{foreach $kategorie['kategorie'] as $kat}
		<tr>
	     	<td class="handle">↕</td>
	     	<td>{$control['kategorieForm'][$kat['id']]['id']->control} {$control['kategorieForm'][$kat['id']]['poradi']->control->class('poradi')}</td>
	     	<td>{$kat['nazev']}</a></td>
	     	{if $kategorie['muze_editovat'] == true}<td><a href="{plink edit, $kat['id']}" title="Úprava kategorie" class="edit">Upravit</a></td>{/if}
		</tr>
	{/foreach}
</tbody>
</table>
{$control['kategorieForm']['save']->control}
{widget kategorieForm end}
{else}
	<p class="warning">Žádné kategorie nebyly nalezeny.</p>
{/if}
