{* Šablona s kontakty *}

<div class="video">
<object height="300" width="400">
	<param name="movie" value="http://www.facebook.com/v/{$key}">
	<param name="allowfullscreen" value="true">
	<param name="allowscriptaccess" value="always" />
	<embed src="http://www.facebook.com/v/{$key}" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="400" height="300">
</object>
</div>

<p><a href="http://www.facebook.com/video/video.php?v={$key}">Otevřít toto video na Facebook.com.</a></p>
