{* Šablona s kontakty *}

<div class="video">
	<object height="296" width="450">
		<param name="movie" value="http://www.stream.cz/object/{$key}">
		<param name="allowfullscreen" value="true">
		<param name="wmode" value="transparent">
		<embed src="http://www.stream.cz/object/{$key}" type="application/x-shockwave-flash" wmode="transparent" allowfullscreen="true" height="354" width="450">
	</object>
</div>

<p><a href="http://www.stream.cz/video/{$key}">Otevřít toto video na Stream.cz</a>.</p>
