{* Šablona s kontakty *}

<div class="video">
<object width="{$sirka}" height="{$vyska}">
	<param name="movie" value="http://www.youtube.com/v/{$key}?version=3&autohide=1&showinfo=1" />
	<param name="wmode" value="transparent" />
	<embed src="http://www.youtube.com/v/{$key}?version=3&autohide=1&showinfo=1" type="application/x-shockwave-flash" width="{$sirka}" height="{$vyska}" />
</object>
</div>

<!--p><a href="http://www.youtube.com/watch?v={$key}">Otevřít toto video na Youtube.com.</a></p-->
